[2024-09-06T07:21:17.231+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-06T07:21:17.262+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data_pipeline.upload_file_to_s3 scheduled__2024-09-05T00:00:00+00:00 [queued]>
[2024-09-06T07:21:17.272+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data_pipeline.upload_file_to_s3 scheduled__2024-09-05T00:00:00+00:00 [queued]>
[2024-09-06T07:21:17.272+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-06T07:21:17.301+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_file_to_s3> on 2024-09-05 00:00:00+00:00
[2024-09-06T07:21:17.308+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=210) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-06T07:21:17.310+0000] {standard_task_runner.py:63} INFO - Started process 211 to run task
[2024-09-06T07:21:17.310+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_data_pipeline', 'upload_file_to_s3', 'scheduled__2024-09-05T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/newspipeline.py', '--cfg-path', '/tmp/tmphssuajnx']
[2024-09-06T07:21:17.312+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask upload_file_to_s3
[2024-09-06T07:21:17.371+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_data_pipeline.upload_file_to_s3 scheduled__2024-09-05T00:00:00+00:00 [running]> on host ca47fb49acc7
[2024-09-06T07:21:17.454+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data_pipeline' AIRFLOW_CTX_TASK_ID='upload_file_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-09-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-05T00:00:00+00:00'
[2024-09-06T07:21:17.454+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-06T07:21:18.398+0000] {newspipeline.py:133} ERROR - File not found: /opt/***/dags/ai_news_articles.csv
[2024-09-06T07:21:18.403+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-06T07:21:18.404+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-06T07:21:18.429+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_data_pipeline, task_id=upload_file_to_s3, run_id=scheduled__2024-09-05T00:00:00+00:00, execution_date=20240905T000000, start_date=20240906T072117, end_date=20240906T072118
[2024-09-06T07:21:18.494+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-06T07:21:18.516+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-06T07:21:18.518+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
