[2024-08-20T23:27:42.679+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: etl_data_pipeline.extract_data manual__2024-08-20T23:25:39.553846+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
