[2024-08-21T00:50:28.017+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-21T00:50:28.172+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data_pipeline.upload_file_to_s3 manual__2024-08-21T00:49:30.528564+00:00 [queued]>
[2024-08-21T00:50:28.226+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data_pipeline.upload_file_to_s3 manual__2024-08-21T00:49:30.528564+00:00 [queued]>
[2024-08-21T00:50:28.227+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-21T00:50:28.243+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_file_to_s3> on 2024-08-21 00:49:30.528564+00:00
[2024-08-21T00:50:28.249+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=99) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-21T00:50:28.250+0000] {standard_task_runner.py:63} INFO - Started process 101 to run task
[2024-08-21T00:50:28.250+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_data_pipeline', 'upload_file_to_s3', 'manual__2024-08-21T00:49:30.528564+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/newspipeline.py', '--cfg-path', '/tmp/tmpz41x0h0o']
[2024-08-21T00:50:28.251+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask upload_file_to_s3
[2024-08-21T00:50:28.294+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_data_pipeline.upload_file_to_s3 manual__2024-08-21T00:49:30.528564+00:00 [running]> on host 986f1fc413c3
[2024-08-21T00:50:28.371+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data_pipeline' AIRFLOW_CTX_TASK_ID='upload_file_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-08-21T00:49:30.528564+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-21T00:49:30.528564+00:00'
[2024-08-21T00:50:28.372+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-21T00:50:29.085+0000] {newspipeline.py:126} ERROR - File not found: /opt/***/dags/ai_news_articles_1.csv
[2024-08-21T00:50:29.086+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-21T00:50:29.087+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-21T00:50:29.096+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_data_pipeline, task_id=upload_file_to_s3, run_id=manual__2024-08-21T00:49:30.528564+00:00, execution_date=20240821T004930, start_date=20240821T005028, end_date=20240821T005029
[2024-08-21T00:50:29.147+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-21T00:50:29.170+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-21T00:50:29.174+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
