[2024-09-06T05:18:48.471+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: etl_data_pipeline.extract_data scheduled__2024-09-05T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
