[2024-08-21T00:15:42.722+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: etl_data_pipeline.load_data_to_postgres manual__2024-08-21T00:00:13.344876+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
