[2024-08-20T23:32:59.053+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-20T23:32:59.077+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_data_pipeline.load_data_to_postgres manual__2024-08-20T23:25:39.553846+00:00 [queued]>
[2024-08-20T23:32:59.083+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_data_pipeline.load_data_to_postgres manual__2024-08-20T23:25:39.553846+00:00 [queued]>
[2024-08-20T23:32:59.084+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-20T23:32:59.096+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_to_postgres> on 2024-08-20 23:25:39.553846+00:00
[2024-08-20T23:32:59.102+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=202) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-20T23:32:59.104+0000] {standard_task_runner.py:63} INFO - Started process 204 to run task
[2024-08-20T23:32:59.104+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_data_pipeline', 'load_data_to_postgres', 'manual__2024-08-20T23:25:39.553846+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/newspipeline.py', '--cfg-path', '/tmp/tmpw8yxy417']
[2024-08-20T23:32:59.105+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask load_data_to_postgres
[2024-08-20T23:32:59.144+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_data_pipeline.load_data_to_postgres manual__2024-08-20T23:25:39.553846+00:00 [running]> on host c84336c364d1
[2024-08-20T23:32:59.217+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_data_pipeline' AIRFLOW_CTX_TASK_ID='load_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-08-20T23:25:39.553846+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-20T23:25:39.553846+00:00'
[2024-08-20T23:32:59.218+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-20T23:32:59.234+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-20T23:32:59.235+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: load_data_to_postgres() missing 3 required positional arguments: 'df', 'table_name', and 'conn_string'
[2024-08-20T23:32:59.246+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_data_pipeline, task_id=load_data_to_postgres, run_id=manual__2024-08-20T23:25:39.553846+00:00, execution_date=20240820T232539, start_date=20240820T233259, end_date=20240820T233259
[2024-08-20T23:32:59.259+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task load_data_to_postgres (load_data_to_postgres() missing 3 required positional arguments: 'df', 'table_name', and 'conn_string'; 204)
[2024-08-20T23:32:59.277+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-20T23:32:59.299+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-20T23:32:59.301+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
